water_dataland:
  target: dev
  outputs:
    dev:
      type: 
      host: 
      user: 
      password: 
      port: 5432
      dbname: ingest
      schema: temp
      threads: 8
      connect_timeout: 10
      sslmode: require